language: python
addons:
   apt:
       packages:
            - libhdf5-serial-dev
            - bedtools
python:
  #- "2.6" # pysam dependency doesn't support it
  - "2.7"
before_install:
  # Download the ucsc binaries
  - wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/twoBitToFa
  - wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigToBedGraph
  - wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bedClip
# command to install dependencies
install: 
  - pip install cython
  - pip install .
# command to run tests
script:
  - mv logging.screenonly.conf logging.conf # disable graypy logging
  - nosetests
